//CHIRAG 10-03-26 (13:40)
//OKAY SO IDEA IS AS FOLLOWS WE WILL DEFINE A SCHEDULER ....ITS BASIC TASK WILL BE TO CALL THE FUNCTION WHENEVER SIGNAL IN 
//SENSTIVITY LIST CHANGES AS IN WE WILL RUN THE FUNCTION ON IT
// NOT I FEEL IT CAN BE A MANY TO M,ANY RELATION AS 1 SIGNAL CHNAGE CAN TRIGGER MANY PROCESS AS WELL AS ONE PROCESS CAN HAVE MANY SIGNALS
// SO THERE ARE ACTUALLY 2 WAYS I CAN DO IT 
// 1. LOOP BASED METHOD WHERE THE SCHEDULER HOLDS LIST OF ALL PROCESSES 
// 2. WRITE A COMPLEX MAP TYPE OF STRUCTURE MYSELF IN C 
// NOW GIVEN THE TIME FRAME AND THE FACT THAT KOLIN SIR HAS REDUCED TIME FROM 80 DAYS TO 60I DO NOT THINK I CAN AFFORD MAKING IT MORE COMPLEX
///NOT TO MENTION I AM ALREADY RUNNING BEHIND DUE TO MY HEALTH ISSUES PAST FEW DAYS 
// IT MAKES SENSE TO ME TO USE LOOP BASED APPROACH FOR NOW AND I CAN ALWAYS OPTIMIZE LATER PART OF DAY 
// SO COMING TO THE HEADER WILL PUT GUARDS, PROCESS.H AND UTILS.H WILL BE NEEDED THEN WE CREATE DYNAMICARRAY OF PROCESS AND CALL IT

#ifndef SCHEDULER_H
#define SCHEDULER_H

#include "process.h"
#include "utils.h"

DYNARRAY_TYPE(Process)
typedef struct
{
DynArray_Process process_ARRAY;
} Scheduler;
Scheduler scheduler_init();
void scheduler_add_process(Scheduler* sch, Process p);
void scheduler_notify(Scheduler* sch, Signal s);
#endif